datalists={%'bigsquare1.mat',...
%'bigsquare2.mat',...
%'bigsquare3.mat',...
'bigsquare1normalheight.mat',...
%'bigsquare2normalheight.mat',...
%'bigsquare3normalheight.mat',...
%'bigsquare1tilted.mat',...
%'bigsquare2tilted.mat',...
};

for i = 1 : length(datalists)
    [output] = compare_MAGEKF_MAINS(datalists{i}, true);
end

plot_result(output);