function out1 = dbtheta_dpsi1(in1,in2,in3)
%DBTHETA_DPSI
%    OUT1 = DBTHETA_DPSI(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023-09-23 17:01:05

% Calculates d(B(psi)*theta)/dPsi
%
%Inputs: dp d Ts omega theta
%
%
d1 = in2(1,:);
d2 = in2(2,:);
d3 = in2(3,:);
dpsi1 = in1(1,:);
dpsi2 = in1(2,:);
dpsi3 = in1(3,:);
dpsi4 = in1(4,:);
dpsi5 = in1(5,:);
dpsi6 = in1(6,:);
th1 = in3(1,:);
th2 = in3(2,:);
th3 = in3(3,:);
th4 = in3(4,:);
th5 = in3(5,:);
th6 = in3(6,:);
th7 = in3(7,:);
th8 = in3(8,:);
t2 = d1.*dpsi5;
t3 = d2.*dpsi4;
t4 = d1.*dpsi6;
t5 = d3.*dpsi4;
t6 = d2.*dpsi6;
t7 = d3.*dpsi5;
t8 = d1.*th4;
t9 = d2.*th6;
t10 = d3.*th7;
t11 = dpsi4.*th4;
t12 = dpsi5.*th6;
t13 = dpsi6.*th7;
t14 = d1.*2.0;
t15 = d2.*2.0;
t16 = d3.*2.0;
t17 = d3.*4.0;
t18 = dpsi1.*2.0;
t19 = dpsi2.*2.0;
t20 = dpsi3.*2.0;
t21 = th5.*2.0;
t22 = th8.*2.0;
t47 = d2.*th8.*-2.0;
t48 = dpsi4.*th5.*-2.0;
t23 = t2.*2.0;
t24 = t3.*2.0;
t25 = t4.*2.0;
t26 = t5.*2.0;
t27 = t2.*4.0;
t28 = t3.*4.0;
t29 = t6.*2.0;
t30 = t7.*2.0;
t31 = dpsi6.*t16;
t32 = t14.*th5;
t33 = t15.*th8;
t35 = dpsi5.*t22;
t36 = dpsi4.*t8;
t37 = dpsi5.*t9;
t38 = dpsi6.*t10;
t39 = -t2;
t41 = -t5;
t42 = -t6;
t40 = -t23;
t43 = -t26;
t44 = -t27;
t45 = -t29;
t49 = dpsi4.*t32;
t50 = dpsi5.*t33;
mt1 = [-t12+t13+t22,th7+dpsi4.*th6-dpsi6.*th8.*2.0,t35+th6-dpsi4.*th7,th7+dpsi6.*t21-dpsi5.*th4,t11-t13+t21,t48+th4+dpsi5.*th7,t35+th6+dpsi5.*t21+dpsi6.*th4,t48+th4-dpsi4.*th8.*2.0-dpsi6.*th6,-t11+t12-t21-t22,t9-t10+t50+th4.*(t6+t7)-th5.*(t31-dpsi5.*t15),t38+th1-th5.*(t17+t20+t28+t40)-th8.*(t16+t20+t28+t40)+th6.*(d1+dpsi1+t7+t45)+th4.*(dpsi2+t4+t15+t43),t37+t47-th2-th5.*(d2.*4.0-t5.*4.0+t19+t25)-th7.*(d1+dpsi1+t30+t42)-th4.*(dpsi3+t16+t24+t39)];
mt2 = [t38-th1+th5.*(t16+t20+t24+t44)+th8.*(t17+t20+t24+t44)-th4.*(d2+dpsi2+t25+t41)-th6.*(dpsi1+t14+t30+t42),-t8+t10+t49+th6.*(t4+t5)-th8.*(t31-dpsi4.*t14),t32+t36+th3+th8.*(d1.*4.0+t7.*4.0+t18+t45)+th7.*(d2+dpsi2+t4+t43)+th6.*(dpsi3+t3+t16+t40),t37+t47+th2+th5.*(t4.*4.0+t15+t19+t43)+th4.*(d3+dpsi3+t3+t40)+th7.*(dpsi1+t7+t14+t45),t32+t36-th3-th8.*(t6.*-4.0+t14+t18+t30)-th6.*(d3+dpsi3+t24+t39)-th7.*(dpsi2+t15+t25+t41),t8-t9+th7.*(t2+t3)+d1.*t48+dpsi5.*t47];
out1 = reshape([mt1,mt2],3,6);
end
